// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFri1y6ksBXJZvgnDKaejGrvzUnwRxEk',
    appId: '1:370700414640:web:c55fb15ca56305d4b0d575',
    messagingSenderId: '370700414640',
    projectId: 'heartrate-82b72',
    authDomain: 'heartrate-82b72.firebaseapp.com',
    storageBucket: 'heartrate-82b72.firebasestorage.app',
    measurementId: 'G-4KLXE10E8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCraP2dZUgMiGuD2CIvbSKV_0JDVPqonfA',
    appId: '1:370700414640:android:a98067f755d42a80b0d575',
    messagingSenderId: '370700414640',
    projectId: 'heartrate-82b72',
    storageBucket: 'heartrate-82b72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRigV868RebQMlEQjUUa_xcWtLcEXR78',
    appId: '1:370700414640:ios:dad5059883526a85b0d575',
    messagingSenderId: '370700414640',
    projectId: 'heartrate-82b72',
    storageBucket: 'heartrate-82b72.firebasestorage.app',
    iosBundleId: 'com.example.heartrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRigV868RebQMlEQjUUa_xcWtLcEXR78',
    appId: '1:370700414640:ios:dad5059883526a85b0d575',
    messagingSenderId: '370700414640',
    projectId: 'heartrate-82b72',
    storageBucket: 'heartrate-82b72.firebasestorage.app',
    iosBundleId: 'com.example.heartrate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKFri1y6ksBXJZvgnDKaejGrvzUnwRxEk',
    appId: '1:370700414640:web:f712fca2661aa724b0d575',
    messagingSenderId: '370700414640',
    projectId: 'heartrate-82b72',
    authDomain: 'heartrate-82b72.firebaseapp.com',
    storageBucket: 'heartrate-82b72.firebasestorage.app',
    measurementId: 'G-CP8DVJBBMK',
  );
}
